import { useState } from 'react'
import { Plus, Search, Edit, MoreHorizontal, Key, Eye, PlusCircle, X, Trash2 } from 'lucide-react'
import { useBackendListState } from '@/hooks/useBackendListState'

interface Expert { id: string; name: string; username: string; phone: string; unit: string; skillType: string; skillProject: string; status: 'active' | 'inactive' }

const initialExperts: Expert[] = [
  { id: '1', name: '刘专家', username: 'liuzj', phone: '13800138101', unit: '清华大学', skillType: '标准编制', skillProject: '核反应堆运行值班员', status: 'active' },
  { id: '2', name: '郑专家', username: 'zhengzj', phone: '13800138102', unit: '华北电力大学', skillType: '题库编制', skillProject: '电气试验员', status: 'active' },
  { id: '3', name: '陈专家', username: 'chenzj', phone: '13800138103', unit: '中国核电工程', skillType: '审题专家', skillProject: '机械设备检修工', status: 'active' },
]

export default function ExpertsPage() {
  const [experts, setExperts] = useBackendListState<Expert>(initialExperts)
  const [search, setSearch] = useState('')
  const [showAdd, setShowAdd] = useState(false)
  const [showEdit, setShowEdit] = useState<Expert | null>(null)
  const [showReset, setShowReset] = useState<Expert | null>(null)
  const [showDelete, setShowDelete] = useState<string | null>(null)
  const [menuOpen, setMenuOpen] = useState<string | null>(null)
  const [addForm, setAddForm] = useState({ name: '', username: '', password: '', phone: '', unit: '', skillType: '标准编制', skillProject: '' })
  const [editForm, setEditForm] = useState<Partial<Expert>>({})
  const [resetPwd, setResetPwd] = useState('')

  const filtered = experts.filter(e => !search || e.name.includes(search) || e.unit.includes(search))
  const toggleStatus = (id: string) => setExperts(prev => prev.map(e => e.id === id ? { ...e, status: e.status === 'active' ? 'inactive' : 'active' } : e))
  const doAdd = () => { setExperts(prev => [{ id: Date.now().toString(), name: addForm.name, username: addForm.username, phone: addForm.phone, unit: addForm.unit, skillType: addForm.skillType, skillProject: addForm.skillProject, status: 'active' }, ...prev]); setAddForm({ name: '', username: '', password: '', phone: '', unit: '', skillType: '标准编制', skillProject: '' }); setShowAdd(false) }
  const doEdit = () => { if (!showEdit) return; setExperts(prev => prev.map(e => e.id === showEdit.id ? { ...e, ...editForm } : e)); setShowEdit(null) }
  const doReset = () => { setShowReset(null); setResetPwd('') }
  const doDelete = (id: string) => { setExperts(prev => prev.filter(e => e.id !== id)); setShowDelete(null) }

  return (
    <div>
      <h1 className="text-xl font-bold text-gray-900 mb-4">开发专家管理</h1>
      <div className="flex items-center justify-between mb-3">
        <div className="relative"><Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="搜索专家姓名/单位..." className="h-9 pl-9 pr-4 border border-gray-200 rounded-md text-sm focus:outline-none focus:border-[#1A56DB] w-72" /></div>
        <button onClick={() => setShowAdd(true)} className="h-9 px-4 bg-[#1A56DB] text-white rounded-md text-sm flex items-center gap-1.5 hover:bg-[#1748B5]"><Plus className="w-4 h-4" /> 新增专家</button>
      </div>
      <div className="bg-white rounded-lg border border-gray-200 overflow-auto">
        <table className="w-full text-sm"><thead className="bg-[#F9FAFB] text-gray-600 font-medium sticky top-0"><tr><th className="px-4 py-3 text-left">姓名</th><th className="px-4 py-3 text-left">登录账号</th><th className="px-4 py-3 text-left">手机号</th><th className="px-4 py-3 text-left">工作单位</th><th className="px-4 py-3 text-left">擅长类型</th><th className="px-4 py-3 text-left">擅长项目</th><th className="px-4 py-3 text-left">状态</th><th className="px-4 py-3 text-left">操作</th></tr></thead>
          <tbody className="divide-y divide-gray-100">{filtered.map(e => (
            <tr key={e.id} className="hover:bg-gray-50">
              <td className="px-4 py-3 font-medium text-gray-900">{e.name}</td><td className="px-4 py-3 text-gray-600">{e.username}</td><td className="px-4 py-3 text-gray-600">{e.phone}</td><td className="px-4 py-3 text-gray-600">{e.unit}</td><td className="px-4 py-3 text-gray-600">{e.skillType}</td><td className="px-4 py-3"><span className="px-2 py-0.5 bg-blue-50 text-blue-700 rounded text-xs">{e.skillProject}</span></td>
              <td className="px-4 py-3"><button onClick={() => toggleStatus(e.id)} className={`px-2 py-0.5 rounded text-xs font-medium ${e.status === 'active' ? 'bg-green-50 text-green-700' : 'bg-gray-100 text-gray-600'}`}>{e.status === 'active' ? '正常' : '停用'}</button></td>
              <td className="px-4 py-3"><div className="flex items-center gap-1 relative"><button onClick={() => { setShowEdit(e); setEditForm(e) }} className="p-1.5 hover:bg-gray-100 rounded-md text-gray-500" title="编辑"><Edit className="w-4 h-4" /></button><button onClick={() => setMenuOpen(menuOpen === e.id ? null : e.id)} className="p-1.5 hover:bg-gray-100 rounded-md text-gray-500"><MoreHorizontal className="w-4 h-4" /></button>
                {menuOpen === e.id && (<div className="absolute right-0 top-full mt-1 w-36 bg-white rounded-lg shadow-lg border border-gray-200 py-1 z-50"><button onClick={() => { setMenuOpen(null) }} className="w-full flex items-center gap-2 px-3 py-2 text-sm text-gray-700 hover:bg-gray-50"><Eye className="w-3.5 h-3.5" /> 查看任务</button><button onClick={() => { setShowReset(e); setMenuOpen(null) }} className="w-full flex items-center gap-2 px-3 py-2 text-sm text-gray-700 hover:bg-gray-50"><Key className="w-3.5 h-3.5" /> 重置密码</button><button onClick={() => { setMenuOpen(null) }} className="w-full flex items-center gap-2 px-3 py-2 text-sm text-gray-700 hover:bg-gray-50"><PlusCircle className="w-3.5 h-3.5" /> 新增擅长</button><button onClick={() => { setShowDelete(e.id); setMenuOpen(null) }} className="w-full flex items-center gap-2 px-3 py-2 text-sm text-red-600 hover:bg-red-50"><Trash2 className="w-3.5 h-3.5" /> 删除</button></div>)}</div></td>
            </tr>
          ))}</tbody></table>
        {filtered.length === 0 && <div className="py-12 text-center text-gray-400 text-sm">暂无数据</div>}
      </div>
      {showAdd && (<div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center" onClick={() => setShowAdd(false)}><div className="bg-white rounded-lg shadow-xl w-[560px]" onClick={e => e.stopPropagation()}><div className="flex items-center justify-between px-6 py-4 border-b border-gray-200"><h3 className="text-base font-semibold text-gray-900">新增专家</h3><button onClick={() => setShowAdd(false)} className="text-gray-400 hover:text-gray-600"><X className="w-5 h-5" /></button></div><div className="p-6 grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-700 mb-1">登录账号 *</label><input value={addForm.username} onChange={v => setAddForm({ ...addForm, username: v.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div><div><label className="block text-sm text-gray-700 mb-1">密码 *</label><input type="password" value={addForm.password} onChange={v => setAddForm({ ...addForm, password: v.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div><div><label className="block text-sm text-gray-700 mb-1">姓名 *</label><input value={addForm.name} onChange={v => setAddForm({ ...addForm, name: v.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div><div><label className="block text-sm text-gray-700 mb-1">手机号</label><input value={addForm.phone} onChange={v => setAddForm({ ...addForm, phone: v.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div><div><label className="block text-sm text-gray-700 mb-1">工作单位</label><input value={addForm.unit} onChange={v => setAddForm({ ...addForm, unit: v.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div><div><label className="block text-sm text-gray-700 mb-1">擅长类型</label><select value={addForm.skillType} onChange={v => setAddForm({ ...addForm, skillType: v.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm"><option>标准编制</option><option>题库编制</option><option>审题专家</option></select></div><div className="col-span-2"><label className="block text-sm text-gray-700 mb-1">擅长项目</label><input value={addForm.skillProject} onChange={v => setAddForm({ ...addForm, skillProject: v.target.value })} placeholder="多个项目用逗号分隔" className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div></div><div className="flex justify-end gap-2 px-6 py-4 border-t border-gray-200 bg-gray-50 rounded-b-lg"><button onClick={() => setShowAdd(false)} className="h-9 px-4 border border-gray-200 rounded-md text-sm hover:bg-gray-100">取消</button><button onClick={doAdd} disabled={!addForm.name || !addForm.username || !addForm.password} className="h-9 px-4 bg-[#1A56DB] text-white rounded-md text-sm disabled:opacity-40">保存</button></div></div></div>)}
      {showEdit && (<div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center" onClick={() => setShowEdit(null)}><div className="bg-white rounded-lg shadow-xl w-[560px]" onClick={e => e.stopPropagation()}><div className="flex items-center justify-between px-6 py-4 border-b border-gray-200"><h3 className="text-base font-semibold text-gray-900">编辑专家</h3><button onClick={() => setShowEdit(null)} className="text-gray-400 hover:text-gray-600"><X className="w-5 h-5" /></button></div><div className="p-6 grid grid-cols-2 gap-4"><div><label className="block text-sm text-gray-700 mb-1">姓名</label><input value={editForm.name || ''} onChange={e => setEditForm({ ...editForm, name: e.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div><div><label className="block text-sm text-gray-700 mb-1">登录账号</label><input value={editForm.username || ''} onChange={e => setEditForm({ ...editForm, username: e.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div><div><label className="block text-sm text-gray-700 mb-1">手机号</label><input value={editForm.phone || ''} onChange={e => setEditForm({ ...editForm, phone: e.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div><div><label className="block text-sm text-gray-700 mb-1">工作单位</label><input value={editForm.unit || ''} onChange={e => setEditForm({ ...editForm, unit: e.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div><div><label className="block text-sm text-gray-700 mb-1">擅长类型</label><select value={editForm.skillType || ''} onChange={e => setEditForm({ ...editForm, skillType: e.target.value })} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm"><option>标准编制</option><option>题库编制</option><option>审题专家</option></select></div></div><div className="flex justify-end gap-2 px-6 py-4 border-t border-gray-200 bg-gray-50 rounded-b-lg"><button onClick={() => setShowEdit(null)} className="h-9 px-4 border border-gray-200 rounded-md text-sm hover:bg-gray-100">取消</button><button onClick={doEdit} className="h-9 px-4 bg-[#1A56DB] text-white rounded-md text-sm">保存</button></div></div></div>)}
      {showReset && (<div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center" onClick={() => setShowReset(null)}><div className="bg-white rounded-lg shadow-xl w-[400px]" onClick={e => e.stopPropagation()}><div className="flex items-center justify-between px-6 py-4 border-b border-gray-200"><h3 className="text-base font-semibold text-gray-900">重置密码 - {showReset.name}</h3><button onClick={() => setShowReset(null)} className="text-gray-400 hover:text-gray-600"><X className="w-5 h-5" /></button></div><div className="p-6"><label className="block text-sm text-gray-700 mb-1">新密码</label><input type="password" value={resetPwd} onChange={e => setResetPwd(e.target.value)} className="w-full h-9 px-3 border border-gray-200 rounded-md text-sm" /></div><div className="flex justify-end gap-2 px-6 py-4 border-t border-gray-200 bg-gray-50 rounded-b-lg"><button onClick={() => setShowReset(null)} className="h-9 px-4 border border-gray-200 rounded-md text-sm hover:bg-gray-100">取消</button><button onClick={doReset} disabled={!resetPwd} className="h-9 px-4 bg-[#1A56DB] text-white rounded-md text-sm disabled:opacity-40">确认重置</button></div></div></div>)}
      {showDelete && (<div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center" onClick={() => setShowDelete(null)}><div className="bg-white rounded-lg shadow-xl w-[400px]" onClick={e => e.stopPropagation()}><div className="p-6 text-center"><div className="w-12 h-12 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-3"><Trash2 className="w-6 h-6 text-red-600" /></div><h3 className="text-lg font-semibold text-gray-900 mb-2">确认删除?</h3></div><div className="flex justify-center gap-3 px-6 pb-6"><button onClick={() => setShowDelete(null)} className="h-9 px-6 border border-gray-200 rounded-md text-sm hover:bg-gray-100">取消</button><button onClick={() => doDelete(showDelete)} className="h-9 px-6 bg-red-600 text-white rounded-md text-sm hover:bg-red-700">确认删除</button></div></div></div>)}
    </div>
  )
}
